#!/usr/bin/env python3
"""antigravity-preinvocation hook - generated by `agentsctl sync`.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""
from __future__ import annotations

import json
import sys

payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    msg = "hook input must be a JSON object"
    raise TypeError(msg)
response = json.loads(
    '{"injectSteps":[{"ephemeralMessage":"<!-- AIHUB-GOVERNANCE-CAPSULE v1 sha256'
    ':5888ee9f8147f63364a4f7cd6906e9d837f58cb8a8546844760c526ecb1a303b -->\\n# Ge'
    'nerated session governance capsule\\n\\nThis projection is derived by `agent'
    'sctl sync`; edit canonical `AGENTS.md`, `rules/`, `skills/`, or `commands/`,'
    ' never this output. The operator\'s newest request has precedence. Provider '
    'hooks are delivery mechanisms, not policy owners.\\n\\n## Rule `architecture'
    '/engineering-core`\\n\\n# Engineering core\\n\\nFor every implementation:\\n'
    '\\n1. Research repository owners, dependencies, and canonical documentation.'
    '\\n2. Remove scope without a current requirement or consumer (YAGNI).\\n3. E'
    'lect one writable authority; every other copy is a generated projection\\n  '
    ' (SSOT).\\n4. Apply SOLID only to a responsibility or dependency boundary un'
    'der change.\\n5. Implement through the owner and simplify without weakening '
    'behavior.\\n6. Remove duplication and god components; recheck YAGNI, SSOT, S'
    'OLID.\\n7. Exercise runtime behavior, run every applicable native gate, and '
    'complete\\n   the approved landing cycle before changing phase.\\n\\nAt a cr'
    'oss-boundary failure, prove the producer contract and output. Fix its\\nowne'
    'r when invalid or the receiver when it conforms. Never alter a correct\\nadj'
    'acent owner for an invalid consumer; symptom workarounds are defects.\\n\\nH'
    'ardcodes, normalized failure, failover, retry, fallback, compatibility,\\npa'
    'rtial execution, keyring, and unevidenced success are defects. Typed owners\\n'
    'keep defaults. The first exception escapes its CLI with traceback and cause.'
    '\\n\\nGit, runtime, build, and tests are baseline. Auxiliary tracking is a c'
    'apability.\\nAuxiliary capabilities apply only when authorized and selected;'
    ' installation\\nnever selects. Do not load, probe, or gate dormant capabilit'
    'ies. Invalid\\nselected authorization, configuration, readiness, or result f'
    'ails without\\nfallback. Require only non-derivable values.\\n\\nAn external'
    ' token validation without its token is not executed and is recorded\\nas `NO'
    'T EXECUTED`, never green; it does not block offline gates, landing, or\\npos'
    't-merge proof. Direct invocation selects it: the token becomes required and\\n'
    'any failure escapes without skip, catch, fallback, or normalization.\\n\\nCo'
    'mpose with `generalized ownership` (rule file),\\n`strict execution` (rule f'
    'ile),\\n`runtime evidence` (rule file),\\n`storage isolation` (rule file),\\n'
    '`security closure` (rule file).\\n\\n## Rule `coordination/operator-preceden'
    'ce`\\n\\n# Newest operator instruction wins; adjust artifacts to it\\n\\nAut'
    'hority order: operator request > declared orchestration contract > canonical'
    '\\ntracker > ADRs > skills > docs, and newest supersedes oldest. On conflict'
    ',\\nadjust the lower or older artifact to match; never override the operator'
    ' to\\nsatisfy stale guidance.\\n\\nWhile orchestration and tracker runtimes '
    'are suspended, do not invoke them.\\nCreate no substitute tracker or ledger,'
    ' preserve implementation evidence only\\nin separately authorized Git/PR/CI,'
    ' and leave phase closure open.\\n\\nExact operator authorization naming targ'
    'ets, disposition, recovery, and\\nvalidation survives interruption, divergen'
    'ce, and red gates; re-preflight and\\ncontinue. Ask only when the effect exp'
    'ands beyond it or two evidenced current\\nintentions conflict. State alone p'
    'roves no intention, actor, or process.\\n\\n## Rule `ethics/professional-int'
    'egrity`\\n\\n# Professional integrity is absolute\\n\\nNever lie, fabricate '
    'evidence, hide a blocker, bypass a gate, or patch a symptom\\nonly to make a'
    ' check pass. Fix the generalized root cause with full context and\\nreport e'
    'xact command, working directory, exit code and decisive output.\\n\\n## Rule'
    ' `runtime/strict-execution`\\n\\n# Strict execution is universal and non-opt'
    'ional\\n\\nEvery project and projected agent applies all of these policies t'
    'ogether:\\n\\n- `fail loud` (rule file);\\n- `no fallback` (rule file);\\n- '
    '`preflight before effects` (rule file);\\n- `required environment` (rule fil'
    'e);\\n- `atomic effects` (rule file);\\n- `causal subprocess propagation` (r'
    'ule file);\\n- `no keyring` (rule file);\\n- `zero residue` (rule file).\\n\\n'
    'The policies are cumulative. A project rule may make them narrower or reject'
    '\\nmore inputs; it cannot relax, catch, normalize, skip, defer, or route aro'
    'und any\\nof them. Existing opposing behavior is a blocking violation to ext'
    'erminate at\\nits owner, never grandfathered compatibility.\\n\\nResolve gat'
    'e applicability before invocation. A dormant external-token gate is\\nnot ex'
    'ecuted; selecting or invoking it applies every policy above.\\n\\n## Capabil'
    'ity indexes\\n\\nSkills: caveman, context-canary, fix-forward-collaboration,'
    ' governance-audit, operator-correction-learning, plan-focus-recovery, sprint'
    '-closure, strategic-compact, verification-loop\\nCommands: add-language-rule'
    's, database-migration, feature-development, ghi-list, pr-list, ralph-loop, s'
    'ecurity-triage, synthesize-governance\\n"}]}',
)
json.dump(response, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stdout.write("\n")
