#!/usr/bin/env python3
"""claude-userpromptsubmit hook - generated by `agentsctl sync`.

Copyright (c) 2025 FLEXT Team. All rights reserved.
SPDX-License-Identifier: MIT
"""
from __future__ import annotations

import json
import sys

payload = json.load(sys.stdin)
if not isinstance(payload, dict):
    msg = "hook input must be a JSON object"
    raise TypeError(msg)
response = json.loads(
    '{"hookSpecificOutput":{"hookEventName":"UserPromptSubmit","additionalContext'
    '":"<!-- AIHUB-GOVERNANCE-CAPSULE v1 sha256:5888ee9f8147f63364a4f7cd6906e9d83'
    '7f58cb8a8546844760c526ecb1a303b -->\\n# Generated session governance capsule'
    '\\n\\nThis projection is derived by `agentsctl sync`; edit canonical `AGENTS'
    '.md`, `rules/`, `skills/`, or `commands/`, never this output. The operator\'s'
    ' newest request has precedence. Provider hooks are delivery mechanisms, not '
    'policy owners.\\n\\n## Rule `architecture/engineering-core`\\n\\n# Engineeri'
    'ng core\\n\\nFor every implementation:\\n\\n1. Research repository owners, d'
    'ependencies, and canonical documentation.\\n2. Remove scope without a curren'
    't requirement or consumer (YAGNI).\\n3. Elect one writable authority; every '
    'other copy is a generated projection\\n   (SSOT).\\n4. Apply SOLID only to a'
    ' responsibility or dependency boundary under change.\\n5. Implement through '
    'the owner and simplify without weakening behavior.\\n6. Remove duplication a'
    'nd god components; recheck YAGNI, SSOT, SOLID.\\n7. Exercise runtime behavio'
    'r, run every applicable native gate, and complete\\n   the approved landing '
    'cycle before changing phase.\\n\\nAt a cross-boundary failure, prove the pro'
    'ducer contract and output. Fix its\\nowner when invalid or the receiver when'
    ' it conforms. Never alter a correct\\nadjacent owner for an invalid consumer'
    '; symptom workarounds are defects.\\n\\nHardcodes, normalized failure, failo'
    'ver, retry, fallback, compatibility,\\npartial execution, keyring, and unevi'
    'denced success are defects. Typed owners\\nkeep defaults. The first exceptio'
    'n escapes its CLI with traceback and cause.\\n\\nGit, runtime, build, and te'
    'sts are baseline. Auxiliary tracking is a capability.\\nAuxiliary capabiliti'
    'es apply only when authorized and selected; installation\\nnever selects. Do'
    ' not load, probe, or gate dormant capabilities. Invalid\\nselected authoriza'
    'tion, configuration, readiness, or result fails without\\nfallback. Require '
    'only non-derivable values.\\n\\nAn external token validation without its tok'
    'en is not executed and is recorded\\nas `NOT EXECUTED`, never green; it does'
    ' not block offline gates, landing, or\\npost-merge proof. Direct invocation '
    'selects it: the token becomes required and\\nany failure escapes without ski'
    'p, catch, fallback, or normalization.\\n\\nCompose with `generalized ownersh'
    'ip` (rule file),\\n`strict execution` (rule file),\\n`runtime evidence` (rul'
    'e file),\\n`storage isolation` (rule file),\\n`security closure` (rule file)'
    '.\\n\\n## Rule `coordination/operator-precedence`\\n\\n# Newest operator ins'
    'truction wins; adjust artifacts to it\\n\\nAuthority order: operator request'
    ' > declared orchestration contract > canonical\\ntracker > ADRs > skills > d'
    'ocs, and newest supersedes oldest. On conflict,\\nadjust the lower or older '
    'artifact to match; never override the operator to\\nsatisfy stale guidance.\\n'
    '\\nWhile orchestration and tracker runtimes are suspended, do not invoke the'
    'm.\\nCreate no substitute tracker or ledger, preserve implementation evidenc'
    'e only\\nin separately authorized Git/PR/CI, and leave phase closure open.\\n'
    '\\nExact operator authorization naming targets, disposition, recovery, and\\n'
    'validation survives interruption, divergence, and red gates; re-preflight an'
    'd\\ncontinue. Ask only when the effect expands beyond it or two evidenced cu'
    'rrent\\nintentions conflict. State alone proves no intention, actor, or proc'
    'ess.\\n\\n## Rule `ethics/professional-integrity`\\n\\n# Professional integr'
    'ity is absolute\\n\\nNever lie, fabricate evidence, hide a blocker, bypass a'
    ' gate, or patch a symptom\\nonly to make a check pass. Fix the generalized r'
    'oot cause with full context and\\nreport exact command, working directory, e'
    'xit code and decisive output.\\n\\n## Rule `runtime/strict-execution`\\n\\n#'
    ' Strict execution is universal and non-optional\\n\\nEvery project and proje'
    'cted agent applies all of these policies together:\\n\\n- `fail loud` (rule '
    'file);\\n- `no fallback` (rule file);\\n- `preflight before effects` (rule f'
    'ile);\\n- `required environment` (rule file);\\n- `atomic effects` (rule fil'
    'e);\\n- `causal subprocess propagation` (rule file);\\n- `no keyring` (rule '
    'file);\\n- `zero residue` (rule file).\\n\\nThe policies are cumulative. A p'
    'roject rule may make them narrower or reject\\nmore inputs; it cannot relax,'
    ' catch, normalize, skip, defer, or route around any\\nof them. Existing oppo'
    'sing behavior is a blocking violation to exterminate at\\nits owner, never g'
    'randfathered compatibility.\\n\\nResolve gate applicability before invocatio'
    'n. A dormant external-token gate is\\nnot executed; selecting or invoking it'
    ' applies every policy above.\\n\\n## Capability indexes\\n\\nSkills: caveman'
    ', context-canary, fix-forward-collaboration, governance-audit, operator-corr'
    'ection-learning, plan-focus-recovery, sprint-closure, strategic-compact, ver'
    'ification-loop\\nCommands: add-language-rules, database-migration, feature-d'
    'evelopment, ghi-list, pr-list, ralph-loop, security-triage, synthesize-gover'
    'nance\\n"}}',
)
json.dump(response, sys.stdout, ensure_ascii=False, separators=(",", ":"))
sys.stdout.write("\n")
