# Generated by `flext-infra codegen conform` for flext_web.
# Clean-machine proof: project bootstrap + canonical make verbs on Alpine
# (musl, POSIX /bin/sh at runtime; bash installed for the project scripts).
FROM alpine:3.21

RUN apk add --no-cache \
      bash ca-certificates coreutils curl git make build-base nodejs util-linux-misc

# uv is an environment-provided executable, intentionally without a project
# patch pin. It installs the declared Python family before canonical bootstrap.
RUN curl -LsSf https://astral.sh/uv/install.sh \
    | env UV_UNMANAGED_INSTALL=/usr/local/bin sh
RUN uv python install 3.13

WORKDIR /workspace
COPY . .

RUN make setup

ENTRYPOINT []
CMD ["/bin/bash", "-lc", "make help"]
