# Generated by `flext_infra codegen conform` for flext_web.
# === SECTION: header (managed) ===
# Source: template (base/ci/docker/alpine.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Alpine
# (musl, POSIX /bin/sh at runtime; bash installed for the project scripts).
FROM alpine:3.21

# === SECTION: base packages (managed) ===
# Source: template (distro-specific package list)
RUN apk add --no-cache \
      bash ca-certificates curl git make build-base icu-dev icu-libs
# End SECTION: base packages

# === SECTION: managed tool bootstrap (managed) ===
# Source: config:python_version, template (installer URLs)
# mise installs the supported Python 3.13 family.
# uv is supplied by the managed environment without a project patch pin.
RUN curl -fsSL https://mise.run | sh
# uv is intentionally supplied by the caller environment; install it explicitly
# in clean-machine images so the project bootstrap can resolve dependencies.
RUN curl -fsSL https://astral.sh/uv/install.sh | sh
# tokei (and any future cargo-backed mise tool) needs a Rust toolchain.
RUN curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
# go is required for mise-managed beads (go:github.com/steveyegge/beads/cmd/bd).
RUN curl -fsSL https://go.dev/dl/go1.23.4.linux-amd64.tar.gz | tar -C /usr/local -xzf - \
    && ln -sf /usr/local/go/bin/go /usr/local/bin/go
ENV PATH="/usr/local/go/bin:/root/.local/bin:/root/.cargo/bin:/root/.local/share/mise/shims:${PATH}"
# End SECTION: managed tool bootstrap

WORKDIR /workspace
COPY . .

# === SECTION: mise install (managed) ===
# Source: computed (reads .mise.toml from copied workspace)
RUN mise trust .mise.toml && mise install --yes
# End SECTION: mise install

# === SECTION: bootstrap soft-pass (managed) ===
# Source: template (external uv.lock/flext-core blocker policy)
# Bootstrap to the external uv.lock boundary: only the known flext-core lock
# soft-passes; any real infra failure fails the image build.
RUN /bin/bash -c 'set +e; \
    output="$(make setup 2>&1)"; status=$?; \
    printf "%s\n" "$output"; \
    if [ "$status" -ne 0 ]; then \
      if printf "%s" "$output" | grep -qi "uv\.lock\|flext-core"; then \
        echo "EXTERNAL BLOCKER (flext-core lock) — soft-passing bootstrap"; \
      else \
        exit "$status"; \
      fi; \
    fi'
# End SECTION: bootstrap soft-pass

ENTRYPOINT []
CMD ["/bin/bash", "-lc", "make help"]
