# Generated by `flext-infra codegen conform` for flext_web.
# Clean-machine proof: project bootstrap + canonical make verbs on Arch Linux.
FROM archlinux:base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN pacman -Syu --noconfirm --needed \
      bash ca-certificates curl git make base-devel \
    && pacman -Scc --noconfirm

# uv is an environment-provided executable, intentionally without a project
# patch pin. It installs the declared Python family before canonical bootstrap.
RUN curl -LsSf https://astral.sh/uv/install.sh \
    | env UV_UNMANAGED_INSTALL=/usr/local/bin sh
RUN uv python install 3.13

WORKDIR /workspace
COPY . .

RUN make setup

ENTRYPOINT []
CMD ["make", "help"]
