# Generated by `flext_infra codegen conform` for flext_web.
# === SECTION: header (managed) ===
# Source: template (base/ci/docker/arch.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Arch Linux.
FROM archlinux:base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === SECTION: base packages (managed) ===
# Source: template (distro-specific package list)
RUN pacman -Syu --noconfirm --needed \
      bash ca-certificates curl git make base-devel \
    && pacman -Scc --noconfirm
# End SECTION: base packages

# === SECTION: managed tool bootstrap (managed) ===
# Source: config:python_version, template (installer URLs)
# mise installs the supported Python 3.13 family.
# uv is supplied by the managed environment without a project patch pin.
RUN curl -fsSL https://mise.run | sh
# uv is intentionally supplied by the caller environment; install it explicitly
# in clean-machine images so the project bootstrap can resolve dependencies.
RUN curl -fsSL https://astral.sh/uv/install.sh | sh
# tokei (and any future cargo-backed mise tool) needs a Rust toolchain.
RUN curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
ENV PATH="/root/.local/bin:/root/.cargo/bin:/root/.local/share/mise/shims:${PATH}"

WORKDIR /workspace
COPY . .

# === SECTION: mise install (managed) ===
# Source: computed (reads .mise.toml from copied workspace)
RUN mise trust .mise.toml && mise install --yes
# End SECTION: mise install

# === SECTION: bootstrap soft-pass (managed) ===
# Source: template (external uv.lock/flext-core blocker policy)
# Bootstrap to the external uv.lock boundary: only the known flext-core lock
# soft-passes; any real infra failure fails the image build.
RUN set +e; \
    output="$(make setup 2>&1)"; status=$?; \
    printf '%s\n' "$output"; \
    if [ "$status" -ne 0 ]; then \
      if printf '%s' "$output" | grep -qi 'uv\.lock\|flext-core'; then \
        echo "EXTERNAL BLOCKER (flext-core lock) — soft-passing bootstrap"; \
      else \
        exit "$status"; \
      fi; \
    fi
# End SECTION: bootstrap soft-pass

ENTRYPOINT []
CMD ["make", "help"]
