# Generated by `flext-infra codegen conform` for flext_web.
# Clean-machine proof: project bootstrap + canonical make verbs on Arch Linux.
FROM archlinux:base

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN pacman -Syu --noconfirm --needed \
      bash ca-certificates curl git make base-devel \
    && pacman -Scc --noconfirm

# mise installs the supported Python 3.13 family.
# uv is supplied by the managed environment without a project patch pin.
RUN curl -fsSL https://mise.run | sh
# uv is intentionally supplied by the caller environment; install it explicitly
# in clean-machine images so the project bootstrap can resolve dependencies.
RUN curl -fsSL https://astral.sh/uv/install.sh | sh
# tokei (and any future cargo-backed mise tool) needs a Rust toolchain.
RUN curl -fsSL https://sh.rustup.rs | sh -s -- -y --default-toolchain stable
ENV PATH="/root/.local/bin:/root/.cargo/bin:/root/.local/share/mise/shims:${PATH}"

WORKDIR /workspace
COPY . .

RUN mise trust .mise.toml && mise install --yes

# Bootstrap to the external uv.lock boundary: only the known flext-core lock
# soft-passes; any real infra failure fails the image build.
RUN set +e; \
    output="$(make setup 2>&1)"; status=$?; \
    printf '%s\n' "$output"; \
    if [ "$status" -ne 0 ]; then \
      if printf '%s' "$output" | grep -qi 'uv\.lock\|flext-core'; then \
        echo "EXTERNAL BLOCKER (flext-core lock) — soft-passing bootstrap"; \
      else \
        exit "$status"; \
      fi; \
    fi

ENTRYPOINT []
CMD ["make", "help"]
