"""Type stubs for docker_ready.py example."""

from flext_web import FlextWebConfig

def create_docker_config() -> FlextWebConfig: ...
def setup_signal_handlers() -> None: ...
def main() -> None: ...
