# syntax=docker/dockerfile:1
# Generated by `flext_infra codegen conform` for flext_web.
# === SECTION: header (managed) ===
# Source: template (base/tests/fixtures/ci/docker/fedora.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Fedora.
FROM fedora:41

SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# === SECTION: base packages (dnf) ===
RUN dnf install -y \
      bash ca-certificates curl git make libatomic \
    && dnf clean all \
    && useradd --create-home --shell /bin/bash runner
# End SECTION: base packages

# === SECTION: native mise bootstrap (managed) ===
# Source: template (clean-machine native mise provisioning)
# mise self-manages: the host installer only provides one mise binary, and
# `make setup` provisions the pinned github:jdx/mise release plus every tool
# from the committed mise.lock as the same unprivileged runtime user.
ARG RUNNER_USER=runner
ENV HOME=/home/${RUNNER_USER}
ENV XDG_DATA_HOME=${HOME}/.local/share \
    XDG_CACHE_HOME=${HOME}/.cache \
    XDG_STATE_HOME=${HOME}/.local/state
RUN curl -fsSL https://mise.run | sh
ENV PATH="${XDG_DATA_HOME}/mise/shims:${HOME}/.local/bin:${PATH}"
WORKDIR /workspace
RUN --mount=type=bind,source=.,target=/source,ro \
    cp -R /source/. /workspace/ \
    && chown -R runner:runner /workspace
COPY --from=git --chown=runner:runner . /workspace/.git/
USER runner
# End SECTION: native mise bootstrap

# === SECTION: bootstrap proof (managed) ===
# Source: template (clean-machine bootstrap through the canonical verb)
# The image exists to PROVE that a clean machine can bootstrap this project
# with nothing but the declared toolchain. It therefore runs the canonical
# setup verb fail-closed: any non-zero status fails the build. An earlier
# revision wrapped this in `set +e` and soft-passed whenever the output
# mentioned uv.lock/flext-core, which turned the proof into a bypass -- a
# broken bootstrap still produced a green image.
# The setup RUN receives GitHub's credential only through a BuildKit secret.
# Never persist build credentials in ARG, ENV, layers, or image configuration.
ENV CI=Y
RUN --mount=type=secret,id=github_token,env=GITHUB_TOKEN,required=true \
    make setup
# End SECTION: bootstrap proof

ENTRYPOINT []
CMD ["make", "help"]
