# syntax=docker/dockerfile:1
# Generated by `flext_infra codegen conform` for flext_web.
# === SECTION: header (managed) ===
# Source: template (base/tests/fixtures/ci/docker/fedora.Dockerfile.j2)
# Free: no
# End SECTION: header
# Clean-machine proof: project bootstrap + canonical make verbs on Fedora.
FROM fedora:41

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

# === SECTION: base packages (managed) ===
# Source: template (distro-specific seed contract)
# The seed is the whole host contract: curl fetches mise, git is what uv shells
# out to for the flext-infra git+https requirement, make invokes the verbs.
RUN dnf install -y \
      bash ca-certificates curl git make libatomic \
    && dnf clean all \
    && useradd --create-home --shell /bin/bash runner
# End SECTION: base packages

# === SECTION: managed tool bootstrap (managed) ===
# Source: generated bin/mise + .mise.toml + mise.lock
# The canonical make setup verb below owns the official newest-Mise bootstrap
# and every locked tool installation as the same unprivileged runtime user.
ENV HOME=/home/runner \
    XDG_DATA_HOME=/home/runner/.local/share \
    XDG_CACHE_HOME=/home/runner/.cache \
    XDG_STATE_HOME=/home/runner/.local/state \
    MISE_DATA_DIR=/home/runner/.local/share/mise \
    MISE_CACHE_DIR=/home/runner/.cache/mise \
    MISE_STATE_DIR=/home/runner/.local/state/mise \
    MISE_TRUSTED_CONFIG_PATHS=/workspace
WORKDIR /workspace
RUN --mount=type=bind,source=.,target=/source,ro \
    cp -R /source/. /workspace/ \
    && chown -R runner:runner /workspace
USER runner
ENV PATH="/home/runner/.local/share/mise/shims:${PATH}"
# End SECTION: managed tool bootstrap

# === SECTION: bootstrap proof (managed) ===
# Source: template (clean-machine bootstrap through the canonical verb)
# The image exists to PROVE that a clean machine can bootstrap this project
# with nothing but the declared toolchain. It therefore runs the canonical
# setup verb fail-closed: any non-zero status fails the build. An earlier
# revision wrapped this in `set +e` and soft-passed whenever the output
# mentioned uv.lock/flext-core, which turned the proof into a bypass -- a
# broken bootstrap still produced a green image.
ENV CI=Y
RUN make setup APPLY=Y
# End SECTION: bootstrap proof

ENTRYPOINT []
CMD ["make", "help"]
