"""Shared text templates used by multiple scripts."""

from __future__ import annotations

__all__ = [
    "GENERATED_HEADER_TEMPLATE",
    "GENERATED_SHELL_HEADER_TEMPLATE",
    "SSOT_HEADER",
    "STATUS_LINE_TEMPLATE",
    "TOC_END",
    "TOC_START",
]


TOC_START: str = "<!-- TOC START -->"
"""Markdown comment marking the start of a table of contents."""

TOC_END: str = "<!-- TOC END -->"
"""Markdown comment marking the end of a table of contents."""

GENERATED_HEADER_TEMPLATE: str = "<!-- Generated from {source} for {project}. -->"
"""Template for generated file header with source and project context.

Usage:
    header = GENERATED_HEADER_TEMPLATE.format(source="script.py", project="flext-core")
"""

GENERATED_SHELL_HEADER_TEMPLATE: str = "# Generated by {source} - DO NOT EDIT\n"
"""Template for shell/YAML generated file headers.

Usage:
    header = GENERATED_SHELL_HEADER_TEMPLATE.format(source="scripts/github/sync_workflows.py")
"""

SSOT_HEADER: str = "<!-- Source of truth: workspace docs/guides/. -->"
"""Markdown comment indicating source of truth location."""

STATUS_LINE_TEMPLATE: str = (
    "PROJECT={project} PHASE={phase} RESULT={result} REASON={reason}"
)
"""Template for status line with project, phase, result, and reason.

Usage:
    status = STATUS_LINE_TEMPLATE.format(
        project="flext-core",
        phase="validation",
        result="PASS",
        reason="All checks passed"
    )
"""
